name: Checks

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Check TypeScript
      run: npm run tsc
    - name: Build
      run: npm run build
