name: Checks

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install
      run: npm ci
      env:
        CI: true
    - name: Lint
      run: npm run lint
      env:
        CI: true
    - name: Flow Type
      run: npm run flow
      env:
        CI: true
    - name: Build
      run: npm run build
      env:
        CI: true
